"""Learning Alembic

Revision ID: 5e0871ed4172
Revises: 
Create Date: 2021-03-02 03:53:10.539012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0871ed4172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('local', sa.VARCHAR(length=64), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verifiedts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('valid', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('salt', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('site_role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'PLEBEIAN', name='siterole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('public_code', sa.TEXT(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_user_to_email_addresses',
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('email_address', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['email_address'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user', 'email_address')
    )
    op.create_table('quiz_sessions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_events',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['image'], ['images.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_session_events',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('quiz_session_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_session_id'], ['quiz_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('identifier', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['image'], ['images.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_session_events__Student___question_finished',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'question_id')
    )
    op.create_table('quiz_session_events__Student___question_started',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'question_id')
    )
    op.create_table('quiz_session_events__Student___quiz_finished',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id')
    )
    op.create_table('quiz_session_events__Student___quiz_started',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id')
    )
    op.create_table('quiz_session_events__Teacher___question_finished',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'question_id')
    )
    op.create_table('quiz_session_events__Teacher___question_modified',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('old_question', sa.INTEGER(), nullable=False),
    sa.Column('new_question', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['new_question'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['old_question'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'old_question')
    )
    op.create_table('quiz_session_events__Teacher___question_removed',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'question_id')
    )
    op.create_table('quiz_session_events__Teacher___question_started',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'question_id')
    )
    op.create_table('quiz_session_events__Teacher___quiz_finished',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id')
    )
    op.create_table('quiz_session_events__Teacher___quiz_started',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id')
    )
    op.create_table('answers_type_essay',
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('answers_type_order',
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.Column('correct_position', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('answers_type_radio',
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.Column('correct', sa.BOOLEAN(), nullable=False),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('answers_type_selection',
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.Column('correct', sa.BOOLEAN(), nullable=False),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('answers_type_short',
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('answers_type_short_answer',
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.Column('correct', sa.TEXT(), nullable=False),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('quiz_session_events__Student___answer_locked_in',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'answer_id')
    )
    op.create_table('quiz_session_events__Student___answer_selected',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'answer_id')
    )
    op.create_table('quiz_session_events__Teacher___answer_added',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('new_answer', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['new_answer'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'new_answer')
    )
    op.create_table('quiz_session_events__Teacher___answer_modified',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('old_answer', sa.INTEGER(), nullable=False),
    sa.Column('new_answer', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['new_answer'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['old_answer'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'old_answer')
    )
    op.create_table('quiz_session_events__Teacher___answer_removed',
    sa.Column('quiz_session_event_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['quiz_session_event_id'], ['quiz_session_events.id'], ),
    sa.PrimaryKeyConstraint('quiz_session_event_id', 'answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_session_events__Teacher___answer_removed')
    op.drop_table('quiz_session_events__Teacher___answer_modified')
    op.drop_table('quiz_session_events__Teacher___answer_added')
    op.drop_table('quiz_session_events__Student___answer_selected')
    op.drop_table('quiz_session_events__Student___answer_locked_in')
    op.drop_table('answers_type_short_answer')
    op.drop_table('answers_type_short')
    op.drop_table('answers_type_selection')
    op.drop_table('answers_type_radio')
    op.drop_table('answers_type_order')
    op.drop_table('answers_type_essay')
    op.drop_table('quiz_session_events__Teacher___quiz_started')
    op.drop_table('quiz_session_events__Teacher___quiz_finished')
    op.drop_table('quiz_session_events__Teacher___question_started')
    op.drop_table('quiz_session_events__Teacher___question_removed')
    op.drop_table('quiz_session_events__Teacher___question_modified')
    op.drop_table('quiz_session_events__Teacher___question_finished')
    op.drop_table('quiz_session_events__Student___quiz_started')
    op.drop_table('quiz_session_events__Student___quiz_finished')
    op.drop_table('quiz_session_events__Student___question_started')
    op.drop_table('quiz_session_events__Student___question_finished')
    op.drop_table('answers')
    op.drop_table('quiz_session_events')
    op.drop_table('questions')
    op.drop_table('room_events')
    op.drop_table('quiz_sessions')
    op.drop_table('link_user_to_email_addresses')
    op.drop_table('images')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('quizzes')
    op.drop_table('email_addresses')
    # ### end Alembic commands ###
