version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
    # Allow changes made to be reflected in the container
    # Useful for development reloading
    - .:/src
  mongo:
    image: library/mongo:4.4
    volumes:
    - data:/data/db
    env_file: .env
    ports:
    - 27017:27017

volumes:
  data:
