/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface QuestionForStudent
 */
export interface QuestionForStudent {
    /**
     * 
     * @type {string}
     * @memberof QuestionForStudent
     */
    previousQuestion?: any;
    /**
     * 
     * @type {string}
     * @memberof QuestionForStudent
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof QuestionForStudent
     */
    query: any;
    /**
     * 
     * @type {string}
     * @memberof QuestionForStudent
     */
    quizId: any;
    /**
     * 
     * @type {Array&lt;AnswerForStudent&gt;}
     * @memberof QuestionForStudent
     */
    answers: any;
}
