/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface QuestionCreate
 */
export interface QuestionCreate {
    /**
     * 
     * @type {string}
     * @memberof QuestionCreate
     */
    previousQuestion?: any;
    /**
     * 
     * @type {string}
     * @memberof QuestionCreate
     */
    query: any;
    /**
     * 
     * @type {string}
     * @memberof QuestionCreate
     */
    quizId: any;
}
