/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface QuizForStudent
 */
export interface QuizForStudent {
    /**
     * 
     * @type {string}
     * @memberof QuizForStudent
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof QuizForStudent
     */
    title: any;
    /**
     * 
     * @type {string}
     * @memberof QuizForStudent
     */
    ownerId: any;
    /**
     * 
     * @type {Array&lt;QuestionForStudent&gt;}
     * @memberof QuizForStudent
     */
    questions: any;
}
