/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StudentResponseCreate
 */
export interface StudentResponseCreate {
    /**
     * 
     * @type {string}
     * @memberof StudentResponseCreate
     */
    quizSessionId: any;
    /**
     * 
     * @type {string}
     * @memberof StudentResponseCreate
     */
    studentId: any;
    /**
     * 
     * @type {string}
     * @memberof StudentResponseCreate
     */
    questionId: any;
    /**
     * 
     * @type {boolean}
     * @memberof StudentResponseCreate
     */
    isCorrect: any;
}
