/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    displayName: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isActive: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isSuperuser: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    number: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    identifierName: any;
}
