/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HTTPValidationError } from '../models';
import { QuizCreate } from '../models';
import { QuizPreview } from '../models';
import { QuizPublic } from '../models';
import { QuizUpdate } from '../models';
/**
 * QuizzesApi - axios parameter creator
 * @export
 */
export const QuizzesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {QuizCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuiz: async (body: QuizCreate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createQuiz.');
            }
            const localVarPath = `/api/v1/quizzes/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2PasswordBearer", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Full Quiz
         * @param {string} ownerId 
         * @param {string} quizName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFullQuiz: async (ownerId: string, quizName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerId' is not null or undefined
            if (ownerId === null || ownerId === undefined) {
                throw new RequiredError('ownerId','Required parameter ownerId was null or undefined when calling getFullQuiz.');
            }
            // verify required parameter 'quizName' is not null or undefined
            if (quizName === null || quizName === undefined) {
                throw new RequiredError('quizName','Required parameter quizName was null or undefined when calling getFullQuiz.');
            }
            const localVarPath = `/api/v1/quizzes/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (ownerId !== undefined) {
                localVarQueryParameter['owner_id'] = ownerId;
            }

            if (quizName !== undefined) {
                localVarQueryParameter['quiz_name'] = quizName;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Raises: Http404InvalidRequestError, Http404QuizNotFound
         * @summary Get Quiz Preview
         * @param {string} quizName 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuizPreview: async (quizName: string, ownerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'quizName' is not null or undefined
            if (quizName === null || quizName === undefined) {
                throw new RequiredError('quizName','Required parameter quizName was null or undefined when calling getQuizPreview.');
            }
            // verify required parameter 'ownerId' is not null or undefined
            if (ownerId === null || ownerId === undefined) {
                throw new RequiredError('ownerId','Required parameter ownerId was null or undefined when calling getQuizPreview.');
            }
            const localVarPath = `/api/v1/quizzes/getPreview`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (quizName !== undefined) {
                localVarQueryParameter['quiz_name'] = quizName;
            }

            if (ownerId !== undefined) {
                localVarQueryParameter['owner_id'] = ownerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quiz Preview By User
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuizPreviewByUser: async (ownerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerId' is not null or undefined
            if (ownerId === null || ownerId === undefined) {
                throw new RequiredError('ownerId','Required parameter ownerId was null or undefined when calling getQuizPreviewByUser.');
            }
            const localVarPath = `/api/v1/quizzes/getPreviewsByUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (ownerId !== undefined) {
                localVarQueryParameter['owner_id'] = ownerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Quiz
         * @param {QuizUpdate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuiz: async (body: QuizUpdate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateQuiz.');
            }
            const localVarPath = `/api/v1/quizzes/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuizzesApi - functional programming interface
 * @export
 */
export const QuizzesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {QuizCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQuiz(body: QuizCreate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPublic>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).createQuiz(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Full Quiz
         * @param {string} ownerId 
         * @param {string} quizName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFullQuiz(ownerId: string, quizName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPublic>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).getFullQuiz(ownerId, quizName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Raises: Http404InvalidRequestError, Http404QuizNotFound
         * @summary Get Quiz Preview
         * @param {string} quizName 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuizPreview(quizName: string, ownerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPreview>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).getQuizPreview(quizName, ownerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Quiz Preview By User
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuizPreviewByUser(ownerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QuizPublic>>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).getQuizPreviewByUser(ownerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update Quiz
         * @param {QuizUpdate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuiz(body: QuizUpdate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPublic>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).updateQuiz(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * QuizzesApi - factory interface
 * @export
 */
export const QuizzesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {QuizCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuiz(body: QuizCreate, options?: any): AxiosPromise<QuizPublic> {
            return QuizzesApiFp(configuration).createQuiz(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Full Quiz
         * @param {string} ownerId 
         * @param {string} quizName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFullQuiz(ownerId: string, quizName: string, options?: any): AxiosPromise<QuizPublic> {
            return QuizzesApiFp(configuration).getFullQuiz(ownerId, quizName, options).then((request) => request(axios, basePath));
        },
        /**
         * Raises: Http404InvalidRequestError, Http404QuizNotFound
         * @summary Get Quiz Preview
         * @param {string} quizName 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuizPreview(quizName: string, ownerId: string, options?: any): AxiosPromise<QuizPreview> {
            return QuizzesApiFp(configuration).getQuizPreview(quizName, ownerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quiz Preview By User
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuizPreviewByUser(ownerId: string, options?: any): AxiosPromise<Array<QuizPublic>> {
            return QuizzesApiFp(configuration).getQuizPreviewByUser(ownerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Quiz
         * @param {QuizUpdate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuiz(body: QuizUpdate, options?: any): AxiosPromise<QuizPublic> {
            return QuizzesApiFp(configuration).updateQuiz(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuizzesApi - object-oriented interface
 * @export
 * @class QuizzesApi
 * @extends {BaseAPI}
 */
export class QuizzesApi extends BaseAPI {
    /**
     * 
     * @summary Create Quiz
     * @param {QuizCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public createQuiz(body: QuizCreate, options?: any) {
        return QuizzesApiFp(this.configuration).createQuiz(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Full Quiz
     * @param {string} ownerId 
     * @param {string} quizName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public getFullQuiz(ownerId: string, quizName: string, options?: any) {
        return QuizzesApiFp(this.configuration).getFullQuiz(ownerId, quizName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Raises: Http404InvalidRequestError, Http404QuizNotFound
     * @summary Get Quiz Preview
     * @param {string} quizName 
     * @param {string} ownerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public getQuizPreview(quizName: string, ownerId: string, options?: any) {
        return QuizzesApiFp(this.configuration).getQuizPreview(quizName, ownerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Quiz Preview By User
     * @param {string} ownerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public getQuizPreviewByUser(ownerId: string, options?: any) {
        return QuizzesApiFp(this.configuration).getQuizPreviewByUser(ownerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update Quiz
     * @param {QuizUpdate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public updateQuiz(body: QuizUpdate, options?: any) {
        return QuizzesApiFp(this.configuration).updateQuiz(body, options).then((request) => request(this.axios, this.basePath));
    }
}
