/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HTTPValidationError } from '../models';
import { ModelObject } from '../models';
import { QuizCreate } from '../models';
import { QuizPublic } from '../models';
import { QuizUpdate } from '../models';
/**
 * QuizzesApi - axios parameter creator
 * @export
 */
export const QuizzesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {QuizCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuizApiV1QuizzesCreatePost: async (body: QuizCreate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createQuizApiV1QuizzesCreatePost.');
            }
            const localVarPath = `/api/v1/quizzes/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("OAuth2PasswordBearer", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Full Quiz
         * @param {string} name 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFullQuizApiV1QuizzesGetGet: async (name: string, ownerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling getFullQuizApiV1QuizzesGetGet.');
            }
            // verify required parameter 'ownerId' is not null or undefined
            if (ownerId === null || ownerId === undefined) {
                throw new RequiredError('ownerId','Required parameter ownerId was null or undefined when calling getFullQuizApiV1QuizzesGetGet.');
            }
            const localVarPath = `/api/v1/quizzes/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (ownerId !== undefined) {
                localVarQueryParameter['owner_id'] = ownerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quiz Title
         * @param {string} name 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuizTitleApiV1QuizzesGetTitleGet: async (name: string, ownerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling getQuizTitleApiV1QuizzesGetTitleGet.');
            }
            // verify required parameter 'ownerId' is not null or undefined
            if (ownerId === null || ownerId === undefined) {
                throw new RequiredError('ownerId','Required parameter ownerId was null or undefined when calling getQuizTitleApiV1QuizzesGetTitleGet.');
            }
            const localVarPath = `/api/v1/quizzes/getTitle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (ownerId !== undefined) {
                localVarQueryParameter['owner_id'] = ownerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Quiz
         * @param {QuizUpdate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuizApiV1QuizzesUpdatePut: async (body: QuizUpdate, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateQuizApiV1QuizzesUpdatePut.');
            }
            const localVarPath = `/api/v1/quizzes/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuizzesApi - functional programming interface
 * @export
 */
export const QuizzesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {QuizCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQuizApiV1QuizzesCreatePost(body: QuizCreate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPublic>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).createQuizApiV1QuizzesCreatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Full Quiz
         * @param {string} name 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFullQuizApiV1QuizzesGetGet(name: string, ownerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPublic>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).getFullQuizApiV1QuizzesGetGet(name, ownerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Quiz Title
         * @param {string} name 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuizTitleApiV1QuizzesGetTitleGet(name: string, ownerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelObject>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).getQuizTitleApiV1QuizzesGetTitleGet(name, ownerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update Quiz
         * @param {QuizUpdate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuizApiV1QuizzesUpdatePut(body: QuizUpdate, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuizPublic>> {
            const localVarAxiosArgs = await QuizzesApiAxiosParamCreator(configuration).updateQuizApiV1QuizzesUpdatePut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * QuizzesApi - factory interface
 * @export
 */
export const QuizzesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {QuizCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuizApiV1QuizzesCreatePost(body: QuizCreate, options?: any): AxiosPromise<QuizPublic> {
            return QuizzesApiFp(configuration).createQuizApiV1QuizzesCreatePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Full Quiz
         * @param {string} name 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFullQuizApiV1QuizzesGetGet(name: string, ownerId: string, options?: any): AxiosPromise<QuizPublic> {
            return QuizzesApiFp(configuration).getFullQuizApiV1QuizzesGetGet(name, ownerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quiz Title
         * @param {string} name 
         * @param {string} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuizTitleApiV1QuizzesGetTitleGet(name: string, ownerId: string, options?: any): AxiosPromise<ModelObject> {
            return QuizzesApiFp(configuration).getQuizTitleApiV1QuizzesGetTitleGet(name, ownerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Quiz
         * @param {QuizUpdate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuizApiV1QuizzesUpdatePut(body: QuizUpdate, options?: any): AxiosPromise<QuizPublic> {
            return QuizzesApiFp(configuration).updateQuizApiV1QuizzesUpdatePut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuizzesApi - object-oriented interface
 * @export
 * @class QuizzesApi
 * @extends {BaseAPI}
 */
export class QuizzesApi extends BaseAPI {
    /**
     * 
     * @summary Create Quiz
     * @param {QuizCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public createQuizApiV1QuizzesCreatePost(body: QuizCreate, options?: any) {
        return QuizzesApiFp(this.configuration).createQuizApiV1QuizzesCreatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Full Quiz
     * @param {string} name 
     * @param {string} ownerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public getFullQuizApiV1QuizzesGetGet(name: string, ownerId: string, options?: any) {
        return QuizzesApiFp(this.configuration).getFullQuizApiV1QuizzesGetGet(name, ownerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Quiz Title
     * @param {string} name 
     * @param {string} ownerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public getQuizTitleApiV1QuizzesGetTitleGet(name: string, ownerId: string, options?: any) {
        return QuizzesApiFp(this.configuration).getQuizTitleApiV1QuizzesGetTitleGet(name, ownerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update Quiz
     * @param {QuizUpdate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuizzesApi
     */
    public updateQuizApiV1QuizzesUpdatePut(body: QuizUpdate, options?: any) {
        return QuizzesApiFp(this.configuration).updateQuizApiV1QuizzesUpdatePut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
